global using System.Numerics;
// global using Raylib_CSharp;
// global using Raylib_CSharp.Apis;
// global using Raylib_CSharp.Colors;
// global using Raylib_CSharp.Shaders;
// global using Raylib_CSharp.Rendering;
global using UwU = RLShooter.App.Editor.ImGuiIntegration.FontAwesome;
global using GUwU = RLShooter.App.Editor.ImGuiIntegration.MaterialIcons;
global using Hexa.NET.Utilities;
global using static Hexa.NET.Utilities.Utils;
global using PhysicsWorld = Box2D.NetStandard.Dynamics.World.World;
global using Hexa.NET.Raylib;
global using static Hexa.NET.Raylib.Raylib;